### ISSUE TITLE
Not possible to update one runner property

### ISSUE THREAD

**Issue by stisti** [ohmu/tjob#3]
When I do

```
tjob runner update --ssh-key=$HOME/.ssh/jenkins_key
```

the command

```
tjob list
```

produces error "x509: certificate signed by unknown authority" even though it worked OK the last time I used it. When I fix the certificate error:

```
tjob runner update --insecure=true ub10
```

When I check the path to ssh key, it has reverted to "id_rsa".

```
tjob runner list
NAME  URL                                           USER    SSH-PORT  SSH-KEY  INSECURE
ub10  https://ultrabuilder10.f-secure.com/jenkins/  tikksa  54410     id_rsa   true
```

It seems to me whenever I use tjob runner update to set one runner property, it reverts the others to their default values.

**Comment by melor** [comment]
Fixed in https://github.com/ohmu/tjob/commit/9e4bd83a03e7f53af86ddfe0697a56f6185df068
