### ISSUE TITLE
Job tags do not like comma

### ISSUE THREAD

**Issue by stisti** [ohmu/tjob#4]
To reproduce

```
$ tjob run -O USER:tikksa -O BRANCH:ro2 -O "TEST:" -T ro2,2 ub10 sandbox-packages
started job: ub10 sandbox-packages 417
$ tjob list -t ro2,2
# nothing printed
$ tjob list --tags
…
ub10    sandbox-packages            417     ro2,2             RUNNING   Aug 18 23:28:58  48s+ 
…
$ tjob list --tag=ro2,2
# nothing printed

Is comma not a valid character to use in job tags?
```

**Comment by melor** [comment]
When running or restarting a job you can specify multiple tags with "-T foo -T bar". "-T foo,bar" will define a single tag named "foo,bar".

When listing jobs, "list -t foo -t bar" will list jobs tagged with "foo" OR "bar". "list -t foo,bar" will only list jobs that are tagged with both "foo" AND "bar".

This behavior is somewhat inconsistent and unobvious, I'll probably do something about it.

**Comment by melor** [comment]
"-T foo,bar" works now the same way as "-T foo -T bar" since https://github.com/ohmu/tjob/commit/f9b474af055dcd631d7aa774df3489cc138ca7cf
