### ISSUE TITLE
include template files into the tjob binary directly?

### ISSUE THREAD

**Issue by sanga** [ohmu/tjob#7]
not a bug but rather a feature request. Would just seem nicer that way to me and there exist various options to do this (though to be fair I haven't actually tried any of them out)

**Comment by melor** [comment]
The few templates included are to be considered as examples and I don't feel it would be beneficial to standardize them by baking them into the binary (at least at this time).

The easiest way to use them:
1.  cp $GOPATH/src/github.com/ohmu/tjob/templates/\* ~/.tjob/
2. tjob list ... --template jobs.md
